version: '2'

services:
  web:
    build: .
    volumes:
      - .:/var/www/open-exam
    ports:
      - "80:80"
    links:
      - db
    # env_file:
    #   - '.env'

  # redis:
  #   image: redis:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file:
      - '.env.db'
